Vagrant.require_version ">= 1.3.5"

Vagrant.configure("2") do |config|

  config.vm.box = "centos/8"
  
  config.vm.define "qweissnaS" do |s|

    s.vm.network "private_network", ip: "192.168.42.110"
    s.vm.hostname = "qweissnaS"
    s.vm.provider "virtualbox" do |vb|
      vb.gui = false 
      vb.memory = "2024"
      vb.cpus=2
   end
    config.vm.provision "file", source: "./manifests", destination: "$HOME/manifests"
    config.vm.provision "shell", path: "setup-script.sh"
  end

  end