apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    app: wilapp
  name: wilapp-app
spec:
  project: argocd-wil-app
  source:
    repoURL: https://github.com/AoedeFeuer/test-cd.git
    targetRevision: main
    path: .
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
