Vagrant.require_version ">= 1.3.5"

Vagrant.configure("2") do |config|

  config.vm.box = "centos/8"
  
  config.vm.define "qweissnaS" do |s|

    s.vm.network "private_network", ip: "192.168.42.110"
    s.vm.hostname = "qweissnaS"
    s.vm.provider "virtualbox" do |vb|
      vb.gui = true 
      vb.memory = "8024"
      vb.cpus=6
      vb.customize ["modifyvm", :id, "--vram", "128"]
   end
  end

  config.disksize.size = '50GB'

  config.vm.provision "shell", inline: <<-SHELL
  sudo yum -y install epel-release
  sudo yum -y update
  sudo yum install -y yum-utils openssh-server openssh-clients wget git snapd
  sudo yum-config-manager \
    --add-repo \
    https://download.docker.com/linux/centos/docker-ce.repo
  sudo yum install -y docker-ce docker-ce-cli containerd.io
  sudo systemctl start docker
    SHELL
  
  config.vm.provision "shell", inline: <<-SHELL
  sudo yum -y groupinstall "Xfce"
  sudo systemctl set-default graphical.target
  sudo systemctl start graphical.target
    SHELL

  config.vm.provision "file", source: "confs", destination: "$HOME/bonus/confs"
  config.vm.provision "file", source: "scripts", destination: "$HOME/bonus/scripts"

  end