Vagrant.require_version ">= 1.3.5"

Vagrant.configure("2") do |config|

  config.vm.box = "centos/8"
  
  config.vm.define "qweissnaS" do |s|

    s.vm.network "private_network", ip: "192.168.42.110"
    s.vm.hostname = "qweissnaS"
    s.vm.provider "virtualbox" do |vb|
      vb.gui = false 
      vb.memory = "1024"
      vb.cpus=1
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
   end

  end

  config.vm.define "qweissnaSW" do |sw|

    sw.vm.network "private_network", ip: "192.168.42.111"
    sw.vm.hostname = "qweissnaSW"
    sw.vm.provider "virtualbox" do |vb| 
      vb.gui = false
      vb.memory = "1024"
      vb.cpus=1
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
   end
  
  end
  
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "scripts/install.yml"
  end

  end